fix: handle app name error and cleanup

diff --git a/create-laravel-app b/create-laravel-app
--- a/create-laravel-app
+++ b/create-laravel-app
@@ -1,58 +1,48 @@
 #!/bin/bash
 
-VERSION="1.0.0-beta.1"
+VERSION="1.0.0"
 
 CYAN="\033[36m"
 GREEN="\033[32m"
 RED="\033[31m"
 YELLOW="\033[33m"
 WHITE="\033[37m"
-
 NC="\033[0m"
 BOLD='\033[1m'
 
+LOG_FILE="/var/log/create-laravel-app.log"
+
 if [[ $1 == "-h" || $1 == "--help" ]]; then
+    cat <<EOF
+-- Create Laravel app ($VERSION) --
 
-    echo ""
-    echo ""
-    echo "-- Create Laravel app ($VERSION) --"
-    echo ""
-    echo ""
-    echo "Usage: create-laravel-app [options]"
-    echo ""
-    echo "Create a new Laravel app with the given services"
-    echo ""
+Usage: create-laravel-app [options]
 
-    echo "By run this script in terminal you will create a laravel app in your current directory or in a specified directory."
-    echo ""
+Create a new Laravel app with the given services.
 
-    echo "Please provide one or more of the supported services (mysql, pgsql, mariadb, redis, memcached, meilisearch, minio, mailpit, selenium, soketi)."
-    echo ""
+By running this script in the terminal you will create a Laravel app in your current directory or in a specified directory.
 
-    echo "If you do not specify which services you would like configured, a default stack of mysql, redis, meilisearch, mailpit, and selenium will be configured."
-    echo ""
+Please provide one or more of the supported services (mysql, pgsql, mariadb, redis, memcached, meilisearch, minio, mailpit, selenium, soketi).
 
-    echo "It use this enpoints to get the docker compose file and the sail file : https://laravel.build/app-name?with=service1,service2,service3"
-    echo ""
+If you do not specify which services you would like configured, a default stack of mysql, redis, meilisearch, mailpit, and selenium will be configured.
 
-    echo "Options:"
-    echo "    -h, --help"
-    echo "    -v, --version"
-    echo "    -d, --directory"
-    echo "    -s, --services"
-    echo "    -n, --name"
-    echo "    -y, -Y, --yes (autostart)"
-    echo ""
+It uses this endpoint to get the Docker Compose file and the Sail file: https://laravel.build/app-name?with=service1,service2,service3
+
+Options:
+    -h, --help
+    -v, --version
+    -d, --directory
+    -s, --services
+    -n, --name
+    -y, -Y, --yes (autostart)
+EOF
     return 0
-
 fi
 
 if [[ $1 == "-v" || $1 == "--version" ]]; then
     printf "\nCreate Laravel app by \e]8;;https://github.com/YannBirba\e\\@YannBirba\e]8;;\e\ version %s \n" "$VERSION"
     return 0
 fi
-
-# -----------------------------------------------------------------------------------
 
 # Ensure that Docker is running...
 if ! docker info >/dev/null 2>&1; then
@@ -63,8 +53,6 @@ if ! docker info >/dev/null 2>&1; then
     echo ""
     return 1
 fi
-
-# -----------------------------------------------------------------------------------
 
 name=""
 dir="."
@@ -107,28 +95,28 @@ if [[ -z "$services" ]]; then
     services="none"
 fi
 
-if [[ -z "$name" ]]; then
+# Please only use alpha-numeric characters, dashes, and underscores.
+if [[ -z "$name" ]] || [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
     echo ""
-    echo "↪ Please provide a name for your app"
+    echo "↪ Please provide a valid name for your app (only alpha-numeric characters, dashes, and underscores are allowed)"
     echo ""
     return 1
 fi
 
+# Validate services
 if [[ $services != "none" ]]; then
-    for service in $(
-        services_list=$services
-        echo "${services_list//,/ }"
-    ); do
+    for service in $(echo "${services//,/ }"); do
         if [[ ! " ${available_services[*]} " =~ " ${service} " ]]; then
             echo ""
-            printf "${BOLD}${YELLOW}↪ Service \"%s\" is not available, available services: \e]8;;https://laravel.com/docs/10.x/installation#choosing-your-sail-services\e\\%s\e]8;;\e\ .${NC}" "$service" "$services_available"
-            echo "[$(date)] -- Service \"$service\" is not available, available services: $services_available ." >>/var/log/create-laravel-app.log
+            printf "${BOLD}${YELLOW}↪ Service \"%s\" is not available, available services: \e]8;;https://laravel.com/docs/11.x/installation#choosing-your-sail-services\e\\%s\e]8;;\e\ .${NC}\n" "$service" "$services_available"
+            echo "[$(date)] -- Service \"$service\" is not available, available services: $services_available ." >>"$LOG_FILE"
             echo ""
             return 1
         fi
     done
 fi
 
+# Determine app directory
 if [[ $dir == "." ]]; then
     dir=$(pwd)
     app_dir="$dir/$name"
@@ -147,39 +135,55 @@ fi
 
 if [[ $services == "none" ]]; then
     echo ""
-    printf "Creating Laravel app named %s with \e]8;;https://laravel.com/docs/10.x/installation#choosing-your-sail-services\e\\default services\e]8;;\e\ in %s" "$name" "$app_dir"
+    printf "Creating Laravel app named %s with \e]8;;https://laravel.com/docs/11.x/installation#choosing-your-sail-services\e\\default services\e]8;;\e\ in %s\n" "$name" "$app_dir"
     echo ""
-    echo "[$(date)] -- Create Laravel app ($VERSION) : named $name with default services on $app_dir" >>/var/log/create-laravel-app.log
 
-    if ! curl -s https://laravel.build/"$name" | bash; then
+    response=$(curl -s -o /tmp/laravel-app-create.response -w '%{http_code}' https://laravel.build/"${name}" || echo "000")
+    HTTP_STATUS=$(tail -n1 <<<"$response")
+    response_body=$(</tmp/laravel-app-create.response)
+
+    if [[ "$HTTP_STATUS" -ge 400 ]] || [[ "$HTTP_STATUS" -eq "000" ]]; then
         echo ""
-        echo -e "${RED}${BOLD}↪ An error occured while creating the app ${NC}"
+        echo -e "${RED}${BOLD}↪ An error occurred while creating the app with status code ${HTTP_STATUS} - Error message: ${response_body} ${NC}"
+        echo /tmp/laravel-app-create.response | tee -a "$LOG_FILE"
         echo ""
-        echo "[$(date)] -- An error occured while creating the app" >>/var/log/create-laravel-app.log
+        echo "[$(date)] -- An error occurred while creating the app" >>"$LOG_FILE"
         return 1
+    else
+        bash "$response_body"
     fi
-    return 0
 else
     echo ""
     echo "Creating Laravel app named $name with $services in $app_dir"
     echo ""
-    echo "[$(date)] -- Create Laravel app ($VERSION) : named $name with $services on $app_dir" >>/var/log/create-laravel-app.log
 
-    if ! curl -s https://laravel.build/"$name"\?with="$services" | bash; then
+    response=$(curl -s -o /tmp/laravel-app-create.response -w '%{http_code}' https://laravel.build/"${name}"?with="${services}" || echo "000")
+    HTTP_STATUS=$(tail -n1 <<<"$response")
+    response_body=$(</tmp/laravel-app-create.response)
+
+    if [[ "$HTTP_STATUS" -ge 400 ]] || [[ "$HTTP_STATUS" -eq "000" ]]; then
         echo ""
-        echo -e "${RED}${BOLD}↪ An error occured while creating the app ${NC}"
+        echo -e "${RED}${BOLD}↪ An error occurred while creating the app with status code ${HTTP_STATUS} - Error message: ${response_body} ${NC}"
+        echo /tmp/laravel-app-create.response | tee -a "$LOG_FILE"
         echo ""
-        echo "[$(date)] -- An error occured while creating the app" >>/var/log/create-laravel-app.log
+        echo "[$(date)] -- An error occurred while creating the app" >>"$LOG_FILE"
         return 1
+    else
+        bash "$response_body"
     fi
 fi
 
 echo ""
-printf "${GREEN}${BOLD}✓ App created successfully created in : \e]8;;code %s\e\\%s\e]8;;\e\ .${NC}" "$app_dir" "$app_dir"
+printf "${GREEN}${BOLD}✓ App created successfully in : \e]8;;code %s\e\\%s\e]8;;\e\ .${NC}\n" "$app_dir" "$app_dir"
 echo ""
 
-cd "$name" || return 1
+# Change to app directory
+if ! cd "$name"; then
+    echo "Failed to change directory to $name" | tee -a "$LOG_FILE"
+    return 1
+fi
 
+# Autostart application if needed
 if [[ $auto_start == "yes" ]]; then
     ./vendor/bin/sail up
 else
